title: OpenMandriva Lx
description: OpenMandriva Lx is an exciting free Desktop Operating System that aims to cater to and interest first time and advanced users alike. It has the breadth and depth of an advanced system but is designed to be simple and straightforward in use.
repository: OpenMandrivaAssociation/rpm
google_analytics: 
show_downloads: false
theme: jekyll-theme-modernist
